### ISSUE TITLE
Label and option for select field swapped?

### ISSUE THREAD

**Issue by elyday** [bastinald/laravel-bootstrap-forms#1]
I am not sure if this is intentional or if it is a bug, so here is my question.

In the following line the array `$options` is split into Key and Value.

https://github.com/bastinald/laravel-bootstrap-forms/blob/c73bd8a0c2595627632181e6b76370581a3e1b15/views/components/select.blade.php#L31

Now, assuming that the Key is the Option and the Value is the Label, we would write the following method:

```
class foo {
    public static function translateOptions(): array
    {
        return [
            'option1' => __('This is option 1'),
            'option2' => __('This is option 2')
        ];
    }
}
```

According to this method the key would be taken over as label (`$label`) and the translated string as option (`$value`). From my point of view this is swapped and should be taken over the other way around, right?

**Comment by bastinald** [comment]
It was made that way by design. 

Think of it as label => value for your array elements. 

I made it this way because I find it's more understandable if you see the label before what the label represents when reading from LtR. 

For example, if it was swapped, something like this would be used:

```
$colors = [
  "#ff0000" => "Red",
  "#0000ff" => "Blue",
];
```

Instead of how you do it now:

```
$colors = [
  "Red" => "#ff0000",
  "Blue" => "#0000ff",
];
```

The second example is much better in my opinion. 

If the array is not associative, then each element value will be used for both the select option label and value.

**Comment by elyday** [comment]
I think this is a pure design decision and in terms of design everyone has a different opinion.

For example, I'm used to something like option values being keys and thus belonging on the left side of the array and the values presented to the user being values on the right side.

This also has something to do with static, unchanged values, and those that can change (due to language settings and the corresponding translation).That is, static values belong as Key on the left side and dynamic changing values on the right side of the array.

**Comment by bastinald** [comment]
You make a good point. 

I'll make the changes later tonight when I'm at my macbook.

**Comment by bastinald** [comment]
done and released. run `composer update` to update to version `1.1.x`.
